### ISSUE TITLE
Missing modid on Forge 1.20.1

### ISSUE THREAD

**Issue by mpustovoi** [mrmelon54/draggable_lists#20]
I installed only Draggable Lists and required Architectury:
![image](https://github.com/mrmelon54/draggable_lists/assets/92390626/83054bff-0841-47a8-998f-ab55570e0434)
I get this:
![image](https://github.com/mrmelon54/draggable_lists/assets/92390626/3e4d1154-c7be-43e9-b2ac-8fb4111a48d1)
Maybe it happens due to incompatibility with latest Forge 47.2.21, otherwise it's just a curse on my Minecraft.
Crash report and latest.log if it helps:
https://gist.github.com/mpustovoi/f9e4aac30b0caac708405a33bc0e02b4

**Comment by mpustovoi** [comment]
I thought this was a problem with the Sinytra Connector, that it would somehow detect your mod as Fabric (due to "all-in-one" .jar) and start porting. However, after shortening the search, I came to a great surprise.

**Comment by mrmelon54** [comment]
I am already aware of this issue and it was fixed for newer versions. Opening the mod jar as a zip file and changing the mod id in `mods.toml` to `draggable` will fix your older version for now.

**Comment by mpustovoi** [comment]
Thanks, it worked.
I'll probably leave this issue until your fixed version is released.

**Comment by mrmelon54** [comment]
This will probably be fixed when I rewrite the codebase and port to older versions, it may take a while.

**Comment by QwertRvg** [comment]
just came across this issue
will you still backport to Forge 1.20.1?

**Comment by QwertRvg** [comment]
i tried this fix, but when launching the game no RPs were loaded, and when opening the RP menu it just crashes

**Comment by mpustovoi** [comment]
I will leave here the full `mods.toml`, which works fine for me, ready for the day.

**Comment by QwertRvg** [comment]
where did you leave it? i'm confused

**Comment by mpustovoi** [comment]
Nowhere, I just forgor

**Comment by mpustovoi** [comment]
`META-INF/mods.toml`:
```toml
modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/draggable_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "draggable"
version = "1.0.1"
displayName = "Draggable Lists"
authors = "MrMelon54"
description = "Draggable resource packs, datapacks and servers"
logoFile = "/icon.png"

[[dependencies.draggable]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
```

**Comment by QwertRvg** [comment]
thanks a lot!

**Comment by QwertRvg** [comment]
thanks!
but it still crashes when i open any kind of screen

**Comment by mrmelon54** [comment]
I saw the increased activity here so I made a fixed build: https://modrinth.com/mod/draggable-lists/version/1.0.1-fix

**Comment by QwertRvg** [comment]
thanks!

**Comment by mpustovoi** [comment]
I don't think it actually has a fix because the new "fixed" file's `META-INF/mods.toml` contains the very same old version with `draggable_lists` ID that crashes on Forge 1.20.1 instead of needed `draggable`:
```toml
modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/draggable_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "draggable_lists"
version = "1.0.1"
displayName = "Draggable Lists"
authors = "MrMelon54"
description = "Draggable resource packs, datapacks and servers"
logoFile = "/icon.png"

[[dependencies.draggable_lists]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
```
